# RoboMaster装甲板检测系统配置文件
# 支持两种模式：传统视觉 vs 神经网络识别

/**:
  ros__parameters:
    # ==========================================================================
    # 基本参数
    # ==========================================================================
    topic_name: "image_raw"              # 图像订阅话题
    display_image: true                  # 是否显示图像
    window_name: "装甲板检测显示"         # 显示窗口名称
    use_sensor_data_qos: true           # 是否使用sensor_data QoS
    
    # ==========================================================================
    # 模式切换 (关键参数)
    # ==========================================================================
    detection_mode: 0                    # 0: 传统视觉模式, 1: 神经网络识别模式
    
    # ==========================================================================
    # 图像预处理参数
    # ==========================================================================
    enable_exposure_enhancement: false   # 是否启用曝光增强
    exposure_gain: 0.8                  # 曝光增益 (0.5-2.0)
    
    # ==========================================================================
    # 模式一：传统视觉模式参数
    # ==========================================================================
    
    # 车辆检测参数
    enable_car_detection: true           # 是否启用车辆检测
    model_path: "/home/pretend/code/src/rm_armor_detect/models/car/car.onnx"
    detection_confidence_threshold: 0.05  # 车辆检测置信度阈值
    
    # 车辆检测专用降曝光参数
    enable_car_exposure_reduction: true  # 是否启用车辆检测降曝光
    car_exposure_reduction_factor: 0.6   # 降曝光因子 (0.1-1.0)
    
    # 灯条检测参数
    binary_threshold: 210                # 二值化阈值 (100-255)
    detect_color: 1                      # 检测颜色 (0:蓝色, 1:红色)
    debug_contours: true                 # 是否显示轮廓调试信息
    
    # ==========================================================================
    # 模式二：神经网络识别模式参数
    # ==========================================================================
    
    # 装甲板检测参数
    armor_model_path: "/home/pretend/code/src/rm_armor_detect/models/armor/armor.onnx"
    armor_confidence_threshold: 0.4      # 装甲板检测置信度阈值 (0.1-0.9)
    
    # 神经网络专用曝光调整参数
    enable_nn_exposure_adjustment: false # 是否启用神经网络曝光调整
    nn_exposure_adjustment_factor: 1.0   # 神经网络曝光调整因子 (0.1-3.0, 1.0=不调整, <1.0=降曝光, >1.0=升曝光)
    
    # ==========================================================================
    # 数字分类器参数 (两种模式共用)
    # ==========================================================================
    enable_number_classification: true   # 是否启用数字分类
    number_model_path: "/home/pretend/code/src/rm_armor_detect/models/number/mlp.onnx"
    number_label_path: "/home/pretend/code/src/rm_armor_detect/models/number/label.txt"
    number_confidence_threshold: 0.7     # 数字分类置信度阈值

# ==========================================================================
# 使用说明:
# 
# 1. 传统视觉模式 (detection_mode: 0):
#    - 使用车辆检测器先找到车辆区域
#    - 在车辆区域内进行灯条检测
#    - 通过几何约束匹配灯条对形成装甲板
#    - 可选择启用数字识别
#    - 适合: 光照条件良好、车辆较清晰的场景
# 
# 2. 神经网络识别模式 (detection_mode: 1):
#    - 直接对整个图像进行端到端的装甲板检测
#    - 使用深度学习模型直接输出装甲板位置和关键点
#    - 更快的检测速度，更好的鲁棒性
#    - 适合: 复杂光照、遮挡、多目标场景
#
# 3. 调试建议:
#    - 先在传统视觉模式下验证基本功能
#    - 如果传统视觉效果不佳，切换到神经网络模式
#    - 根据实际场景调整置信度阈值
#    - 开启debug_contours可以看到更多调试信息
# ========================================================================== 